apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pythonapp.fullname" . }}-secret
  labels:
    {{- include "pythonapp.labels" . | nindent 4 }}
data:
  dbpass: {{ .Values.mongodbdata.password | b64enc }}