apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pythondb.fullname" . }}-cm
  labels:
    {{- include "pythondb.labels" . | nindent 4 }}
data:
  MONGO_INITDB_DATABASE: {{ .Values.mongodbdata.dbname }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodbdata.username }}
  init-db.js: |-
    {{- .Files.Get "init-db.js" | nindent 4 }}