apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pythondb.fullname" . }}-secret
  labels:
    {{- include "pythondb.labels" . | nindent 4 }}
data:
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodbdata.password | b64enc }}