apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: appdeploy
  name: appservice
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31010
  selector:
    app: appdeploy
  type: NodePort
status:
  loadBalancer: {}
