apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dbdeploy
  name: dbservice
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: dbdeploy
status:
  loadBalancer: {}
